/* Taste Buddy — catalog, recipes, quiz, amounts, blocked lists */
(function(){
const C=(name,emoji,cat)=>({name,emoji,cat});
const CATS=['Produce','Meat & Seafood','Dairy & Eggs','Grains & Pasta','Spices','Condiments','Canned & Jarred','Frozen & Ice','Baking & Nuts','Drinks & Extras'];
const CATALOG=[
// Produce
C('onion','🧅','Produce'),C('red onion','🧅','Produce'),C('shallot','🧅','Produce'),C('garlic','🧄','Produce'),C('ginger','🫚','Produce'),C('tomato','🍅','Produce'),C('cherry tomatoes','🍅','Produce'),C('bell pepper','🫑','Produce'),C('jalapeño','🌶️','Produce'),C('carrot','🥕','Produce'),C('celery','🥬','Produce'),C('potato','🥔','Produce'),C('sweet potato','🍠','Produce'),C('broccoli','🥦','Produce'),C('cauliflower','🥦','Produce'),C('spinach','🥬','Produce'),C('kale','🥬','Produce'),C('cabbage','🥬','Produce'),C('lettuce','🥗','Produce'),C('arugula','🌿','Produce'),C('cucumber','🥒','Produce'),C('zucchini','🥒','Produce'),C('eggplant','🍆','Produce'),C('mushrooms','🍄','Produce'),C('green onion','🌱','Produce'),C('leek','🌱','Produce'),C('corn','🌽','Produce'),C('green beans','🫛','Produce'),C('asparagus','🌿','Produce'),C('avocado','🥑','Produce'),C('lemon','🍋','Produce'),C('lime','🍋‍🟩','Produce'),C('orange','🍊','Produce'),C('apple','🍎','Produce'),C('banana','🍌','Produce'),C('strawberries','🍓','Produce'),C('blueberries','🫐','Produce'),C('mango','🥭','Produce'),C('cilantro','🌿','Produce'),C('parsley','🌿','Produce'),C('basil','🌿','Produce'),C('mint','🌿','Produce'),C('dill','🌿','Produce'),C('thyme','🌿','Produce'),C('rosemary','🌿','Produce'),C('fennel','🌿','Produce'),C('beets','🍠','Produce'),C('butternut squash','🎃','Produce'),
// Meat & Seafood
C('chicken breast','🍗','Meat & Seafood'),C('chicken thighs','🍗','Meat & Seafood'),C('whole chicken','🍗','Meat & Seafood'),C('ground beef','🥩','Meat & Seafood'),C('steak','🥩','Meat & Seafood'),C('ground turkey','🦃','Meat & Seafood'),C('pork chops','🥩','Meat & Seafood'),C('bacon','🥓','Meat & Seafood'),C('ham','🍖','Meat & Seafood'),C('sausage','🌭','Meat & Seafood'),C('chorizo','🌭','Meat & Seafood'),C('lamb','🍖','Meat & Seafood'),C('salmon','🐟','Meat & Seafood'),C('white fish','🐟','Meat & Seafood'),C('shrimp','🦐','Meat & Seafood'),C('mussels','🦪','Meat & Seafood'),C('scallops','🦪','Meat & Seafood'),C('tofu','⬜','Meat & Seafood'),
// Dairy & Eggs
C('eggs','🥚','Dairy & Eggs'),C('butter','🧈','Dairy & Eggs'),C('milk','🥛','Dairy & Eggs'),C('buttermilk','🥛','Dairy & Eggs'),C('heavy cream','🥛','Dairy & Eggs'),C('sour cream','🥛','Dairy & Eggs'),C('yogurt','🥛','Dairy & Eggs'),C('greek yogurt','🥛','Dairy & Eggs'),C('cream cheese','🧀','Dairy & Eggs'),C('cheddar','🧀','Dairy & Eggs'),C('mozzarella','🧀','Dairy & Eggs'),C('parmesan','🧀','Dairy & Eggs'),C('feta','🧀','Dairy & Eggs'),C('goat cheese','🧀','Dairy & Eggs'),C('blue cheese','🧀','Dairy & Eggs'),C('ricotta','🧀','Dairy & Eggs'),C('halloumi','🧀','Dairy & Eggs'),
// Grains & Pasta
C('rice','🍚','Grains & Pasta'),C('jasmine rice','🍚','Grains & Pasta'),C('brown rice','🍚','Grains & Pasta'),C('arborio rice','🍚','Grains & Pasta'),C('pasta','🍝','Grains & Pasta'),C('spaghetti','🍝','Grains & Pasta'),C('penne','🍝','Grains & Pasta'),C('orzo','🍝','Grains & Pasta'),C('rice noodles','🍜','Grains & Pasta'),C('egg noodles','🍜','Grains & Pasta'),C('ramen noodles','🍜','Grains & Pasta'),C('bread','🍞','Grains & Pasta'),C('sourdough bread','🍞','Grains & Pasta'),C('tortillas','🫓','Grains & Pasta'),C('pita','🫓','Grains & Pasta'),C('couscous','🍚','Grains & Pasta'),C('quinoa','🌾','Grains & Pasta'),C('oats','🌾','Grains & Pasta'),C('polenta','🌽','Grains & Pasta'),
// Spices
C('salt','🧂','Spices'),C('black pepper','🧂','Spices'),C('cumin','🌶️','Spices'),C('coriander','🌿','Spices'),C('paprika','🌶️','Spices'),C('smoked paprika','🌶️','Spices'),C('chili powder','🌶️','Spices'),C('chili flakes','🌶️','Spices'),C('cayenne','🌶️','Spices'),C('curry powder','🍛','Spices'),C('garam masala','🍛','Spices'),C('turmeric','🟡','Spices'),C('cinnamon','🟤','Spices'),C('nutmeg','🟤','Spices'),C('oregano','🌿','Spices'),C('bay leaves','🍃','Spices'),C('za\'atar','🌿','Spices'),C('five spice','🍛','Spices'),C('saffron','🟠','Spices'),
// Condiments
C('olive oil','🫒','Condiments'),C('vegetable oil','🛢️','Condiments'),C('sesame oil','🛢️','Condiments'),C('soy sauce','🍶','Condiments'),C('fish sauce','🍶','Condiments'),C('oyster sauce','🍶','Condiments'),C('hoisin sauce','🍶','Condiments'),C('sriracha','🌶️','Condiments'),C('hot sauce','🌶️','Condiments'),C('ketchup','🍅','Condiments'),C('mustard','🟡','Condiments'),C('dijon mustard','🟡','Condiments'),C('mayonnaise','⬜','Condiments'),C('honey','🍯','Condiments'),C('maple syrup','🍁','Condiments'),C('rice vinegar','🍶','Condiments'),C('balsamic vinegar','🍶','Condiments'),C('red wine vinegar','🍶','Condiments'),C('apple cider vinegar','🍶','Condiments'),C('worcestershire sauce','🍶','Condiments'),C('tahini','🥜','Condiments'),C('miso paste','🍲','Condiments'),C('gochujang','🌶️','Condiments'),C('harissa','🌶️','Condiments'),C('pesto','🌿','Condiments'),C('salsa','🍅','Condiments'),C('bbq sauce','🍖','Condiments'),C('green curry paste','🍛','Condiments'),
// Canned & Jarred
C('canned tomatoes','🥫','Canned & Jarred'),C('tomato paste','🥫','Canned & Jarred'),C('chickpeas','🫘','Canned & Jarred'),C('black beans','🫘','Canned & Jarred'),C('kidney beans','🫘','Canned & Jarred'),C('white beans','🫘','Canned & Jarred'),C('lentils','🫘','Canned & Jarred'),C('coconut milk','🥥','Canned & Jarred'),C('chicken broth','🍲','Canned & Jarred'),C('vegetable broth','🍲','Canned & Jarred'),C('beef broth','🍲','Canned & Jarred'),C('canned tuna','🐟','Canned & Jarred'),C('olives','🫒','Canned & Jarred'),C('capers','🫒','Canned & Jarred'),C('anchovies','🐟','Canned & Jarred'),C('artichoke hearts','🌿','Canned & Jarred'),C('roasted red peppers','🫑','Canned & Jarred'),C('pickles','🥒','Canned & Jarred'),
// Frozen & Ice
C('frozen peas','🫛','Frozen & Ice'),C('frozen corn','🌽','Frozen & Ice'),C('frozen spinach','🥬','Frozen & Ice'),C('frozen berries','🫐','Frozen & Ice'),C('frozen edamame','🫛','Frozen & Ice'),C('frozen dumplings','🥟','Frozen & Ice'),C('puff pastry','🥐','Frozen & Ice'),C('frozen fries','🍟','Frozen & Ice'),C('ice cream','🍨','Frozen & Ice'),
// Baking & Nuts
C('flour','🌾','Baking & Nuts'),C('sugar','🍬','Baking & Nuts'),C('brown sugar','🟤','Baking & Nuts'),C('powdered sugar','🍬','Baking & Nuts'),C('baking powder','🥄','Baking & Nuts'),C('baking soda','🥄','Baking & Nuts'),C('yeast','🥖','Baking & Nuts'),C('cornstarch','🥄','Baking & Nuts'),C('cocoa powder','🍫','Baking & Nuts'),C('chocolate chips','🍫','Baking & Nuts'),C('dark chocolate','🍫','Baking & Nuts'),C('vanilla extract','🟤','Baking & Nuts'),C('almonds','🥜','Baking & Nuts'),C('walnuts','🥜','Baking & Nuts'),C('cashews','🥜','Baking & Nuts'),C('peanuts','🥜','Baking & Nuts'),C('pecans','🥜','Baking & Nuts'),C('pistachios','🥜','Baking & Nuts'),C('pine nuts','🥜','Baking & Nuts'),C('peanut butter','🥜','Baking & Nuts'),C('sesame seeds','⚪','Baking & Nuts'),C('breadcrumbs','🍞','Baking & Nuts'),C('panko','🍞','Baking & Nuts'),C('coconut flakes','🥥','Baking & Nuts'),C('raisins','🍇','Baking & Nuts'),C('dates','🌴','Baking & Nuts'),
// Drinks & Extras
C('coffee','☕','Drinks & Extras'),C('tea','🍵','Drinks & Extras'),C('white wine','🍷','Drinks & Extras'),C('red wine','🍷','Drinks & Extras'),C('orange juice','🍊','Drinks & Extras'),C('sparkling water','🫧','Drinks & Extras'),C('kimchi','🥬','Drinks & Extras'),C('nori','🟩','Drinks & Extras'),C('nutritional yeast','🟡','Drinks & Extras')
];
const STAPLES_PRESET=['salt','black pepper','olive oil','vegetable oil','flour','sugar','brown sugar','rice','pasta','canned tomatoes','chickpeas','black beans','garlic','onion','butter','eggs','soy sauce','honey','chili flakes','oats'];
// Always assumed present, never counted missing (head-noun match; specialty oils excluded in engine)
const ASSUMED=['salt','pepper','water','oil','sugar','flour'];
const R=(id,title,emoji,category,cuisine,time,difficulty,calories,tags,ingredients,steps,note,pcf,tone)=>({id,title,emoji,category,cuisine,time,difficulty,calories,tags,ingredients,steps,note,pcf,tone});
const RECIPES=[
R('r01','Garlic butter salmon','🐟','Mains','Mediterranean',20,'Easy',520,['fast','healthy','high-protein','impress'],['salmon','butter','garlic','lemon','parsley','olive oil'],['Pat the salmon dry and season well on both sides.','Sear skin-side down in olive oil over medium-high, 4 minutes, until the skin releases.','Flip, drop the heat, and add butter and garlic. Baste for 2–3 minutes.','Off the heat, squeeze over lemon and shower with parsley.'],'Basting is the whole trick — tilt the pan and spoon.',[42,3,36],'fresh'),
R('r02','Weeknight chicken fried rice','🍚','Quick & Easy','Chinese',20,'Easy',480,['fast','cheap','one-pan'],['chicken breast','rice','eggs','frozen peas','green onion','soy sauce','sesame oil','garlic','ginger'],['Scramble the eggs hard in a screaming wok; set aside.','Stir-fry diced chicken until golden, then garlic and ginger for 30 seconds.','Add cold day-old rice, pressing it into the heat. Let it crisp.','Peas, soy, sesame oil, eggs back in. Toss and top with green onion.'],'Day-old rice or nothing. Fresh rice steams; old rice fries.',[31,52,14],'warm'),
R('r03','Creamy tuscan chicken','🍗','Comfort Food','Italian',35,'Medium',640,['comfort','impress','high-protein'],['chicken breast','heavy cream','spinach','cherry tomatoes','parmesan','garlic','olive oil'],['Sear seasoned chicken until deeply golden, 5 minutes a side. Rest on a plate.','Soften garlic in the same pan, add tomatoes until they blister.','Pour in cream, melt in parmesan, wilt the spinach.','Return the chicken and simmer 5 minutes until glossy.'],'The pan crust is flavor — don\'t wash it, deglaze it.',[46,10,42],'heat'),
R('r04','One-pot tomato basil pasta','🍝','Quick & Easy','Italian',25,'Easy',540,['cheap','comfort','one-pan','vegetarian'],['spaghetti','canned tomatoes','garlic','basil','olive oil','parmesan','chili flakes'],['Sizzle sliced garlic and chili flakes in olive oil until fragrant.','Add tomatoes, a can of water, and the dry spaghetti straight in.','Simmer 11 minutes, turning the pasta as it softens into the sauce.','Finish with torn basil and a snowfall of parmesan.'],'The starch stays in the pot — that\'s why it goes silky.',[16,72,18],'heat'),
R('r05','Shakshuka','🍳','Breakfast','Middle Eastern',30,'Easy',380,['healthy','cheap','vegetarian','one-pan'],['eggs','canned tomatoes','bell pepper','onion','garlic','cumin','paprika','feta','parsley'],['Soften onion and pepper in olive oil until sweet, 8 minutes.','Add garlic, cumin and paprika; bloom 1 minute.','Pour in tomatoes and simmer to a thick, spoonable sauce.','Nest in the eggs, lid on, 5–6 minutes for jammy yolks. Feta and parsley over.'],'Serve from the pan. Bread is not optional.',[18,24,22],'heat'),
R('r06','Fluffy buttermilk pancakes','🥞','Breakfast','American',25,'Easy',460,['comfort','sweet','cheap'],['flour','buttermilk','eggs','butter','sugar','baking powder','maple syrup'],['Whisk dry. Whisk wet. Fold together until *just* combined — lumps are good.','Rest the batter 10 minutes while the pan heats low and slow.','Ladle, wait for bubbles to ring the edge, flip once.','Stack high, butter between layers, syrup over the cliff edges.'],'Overmixing is the only way to ruin these.',[12,64,16],'warm'),
R('r07','Miso ramen with a jammy egg','🍜','Mains','Japanese',35,'Medium',520,['comfort','soup'],['ramen noodles','miso paste','chicken broth','eggs','green onion','garlic','ginger','sesame oil','nori'],['Lower eggs into boiling water for 6:30 exactly, then ice bath.','Sweat garlic and ginger in sesame oil; whisk in miso, then broth.','Simmer gently — never boil miso — while the noodles cook separately.','Noodles in bowls, broth over, halved egg, green onion, a sail of nori.'],'6:30 is the number. Set a real timer.',[24,58,18],'earth'),
R('r08','15-minute garlic noodles','🍜','Quick & Easy','Vietnamese',15,'Easy',430,['fast','cheap'],['egg noodles','garlic','butter','soy sauce','oyster sauce','green onion','parmesan'],['Boil noodles; save a mug of the water.','Melt butter with a small mountain of minced garlic — golden, not brown.','Toss in noodles, soy, oyster sauce and a splash of noodle water.','Off heat: parmesan and green onion. Trust it.'],'The parmesan is the secret handshake.',[14,58,16],'warm'),
R('r09','Chicken tikka masala','🍛','Mains','Indian',50,'Medium',680,['comfort','impress','spicy'],['chicken thighs','yogurt','garam masala','turmeric','canned tomatoes','heavy cream','garlic','ginger','onion','rice'],['Marinate chicken in yogurt, garam masala and turmeric — 20 minutes minimum.','Char the chicken under a hot broiler; it should catch at the edges.','Simmer onion, garlic, ginger and tomatoes into a thick gravy; blend smooth.','Cream in, chicken in, simmer 10 minutes. Serve over rice.'],'The char is doing half the work here.',[44,58,30],'heat'),
R('r10','Chana masala','🫘','Healthy','Indian',30,'Easy',420,['vegan','cheap','healthy','spicy'],['chickpeas','onion','garlic','ginger','canned tomatoes','cumin','garam masala','turmeric','cilantro','rice'],['Fry onion hard until edges brown — this is the base note.','Garlic, ginger, spices: bloom 1 minute until the kitchen smells serious.','Tomatoes and chickpeas, simmer 15 minutes until thick.','Mash a few chickpeas to thicken. Cilantro over rice.'],'Canned chickpeas are fine. Everyone uses them.',[16,68,10],'fresh'),
R('r11','Weeknight beef tacos','🌮','Mains','Mexican',25,'Easy',560,['fast','comfort','cheap'],['ground beef','tortillas','onion','garlic','chili powder','cumin','cheddar','lettuce','tomato','sour cream','lime'],['Brown the beef in a dry hot pan; pour off nothing — season into it.','Onion, garlic, chili powder, cumin, splash of water. Simmer 5 minutes.','Char tortillas directly over the flame, 10 seconds a side.','Build: beef, cheddar, lettuce, tomato, sour cream, lime.'],'Charring the tortilla is 90% of restaurant flavor.',[34,42,28],'heat'),
R('r12','Sheet-pan chicken fajitas','🫑','Quick & Easy','Mexican',30,'Easy',490,['one-pan','fast','healthy'],['chicken breast','bell pepper','onion','tortillas','chili powder','cumin','lime','sour cream'],['Slice chicken, peppers and onion into ribbons; toss with spices and oil.','One sheet pan, 220°C, 18 minutes. Don\'t crowd it.','Broil the last 2 minutes for real char.','Pile into warm tortillas with lime and sour cream.'],'Crowded pans steam. Two pans beat one full one.',[38,40,16],'heat'),
R('r13','Bibimbap bowls','🍚','Mains','Korean',40,'Medium',560,['healthy','impress','spicy'],['rice','ground beef','spinach','carrot','mushrooms','eggs','gochujang','sesame oil','garlic','sesame seeds'],['Season beef with garlic and soy; brown and set aside.','Sauté spinach, carrots and mushrooms separately — each gets sesame oil and salt.','Fry eggs crispy-edged, yolks loose.','Rice in bowls, vegetables in neat wedges, beef, egg on top, gochujang to taste.'],'The mix at the table is the whole point. Go in with the spoon.',[30,62,20],'heat'),
R('r14','Kimchi fried rice','🍚','Quick & Easy','Korean',20,'Easy',470,['fast','cheap','spicy','one-pan'],['rice','kimchi','eggs','green onion','sesame oil','soy sauce','butter'],['Chop kimchi; fry it in butter until the edges caramelize.','Add cold rice and press flat. Leave it alone for 2 minutes — crust.','Splash of kimchi juice and soy; toss.','Top with a fried egg and green onion.'],'Old, sour kimchi makes the best version.',[14,60,18],'heat'),
R('r15','Thai green curry','🍛','Mains','Thai',35,'Medium',610,['spicy','comfort','impress'],['green curry paste','coconut milk','chicken thighs','green beans','bell pepper','fish sauce','lime','basil','rice'],['Fry the curry paste in the thick top of the coconut milk until it splits and smells sharp.','Add chicken; coat and sear in the paste.','Rest of the coconut milk, then beans and peppers; simmer 12 minutes.','Season with fish sauce and lime. Basil off the heat. Rice underneath.'],'Frying the paste first is the difference between soup and curry.',[36,44,34],'fresh'),
R('r16','Shrimp pad thai','🍤','Mains','Thai',30,'Medium',580,['impress'],['rice noodles','shrimp','eggs','fish sauce','lime','peanuts','green onion','garlic','sugar','rice vinegar'],['Soak rice noodles in hot tap water 20 minutes — floppy but not soft.','Stir fish sauce, sugar, vinegar and lime into a sauce.','Hard sear shrimp; push aside, scramble eggs in the same wok.','Noodles and sauce in; toss over max heat 2 minutes. Peanuts and green onion.'],'Everything ready before the wok goes on. It moves fast.',[30,64,18],'warm'),
R('r17','Proper greek salad','🥗','Sides','Greek',15,'Easy',320,['salad','healthy','fast','vegetarian'],['cucumber','tomato','red onion','feta','olives','olive oil','oregano','lemon'],['Cut tomatoes and cucumber into big, confident chunks.','Shave the red onion paper-thin; soak in cold water 5 minutes to tame it.','Everything in a bowl with olives; slab of feta on top, never crumbled.','Olive oil, lemon, oregano. Toss at the table.'],'No lettuce. That\'s the rule.',[9,14,26],'fresh'),
R('r18','Lemon chicken orzo soup','🍋','Mains','Greek',35,'Easy',380,['soup','healthy','comfort'],['orzo','chicken broth','chicken breast','carrot','celery','onion','lemon','dill','eggs'],['Sweat onion, carrot and celery until soft.','Broth in, chicken in; poach 12 minutes, then shred it.','Cook the orzo right in the pot.','Whisk eggs with lemon, temper with hot broth, stir back in — silky, not scrambled. Dill to finish.'],'Temper slowly. Hot broth into eggs, never the reverse.',[28,34,10],'fresh'),
R('r19','Tomato soup & grilled cheese','🍅','Comfort Food','American',30,'Easy',620,['soup','comfort','cheap','vegetarian'],['canned tomatoes','onion','garlic','heavy cream','bread','cheddar','butter','basil'],['Melt onion and garlic in butter until translucent.','Tomatoes and a cup of water; simmer 15, then blend velvet-smooth with cream.','Butter the *outside* of the bread. Low heat, cheddar inside, patience.','Flip when deep gold. Cut diagonally. Dunk.'],'Low and slow on the sandwich — crunch needs time.',[20,52,34],'heat'),
R('r20','Crispy smashed potatoes','🥔','Sides','American',45,'Easy',340,['vegetarian','cheap'],['potato','olive oil','garlic','rosemary','parmesan','sour cream'],['Boil small potatoes in heavily salted water until a knife slides in.','Smash each flat on an oiled sheet pan with a mug.','Olive oil, garlic, rosemary over; roast at 230°C for 25 minutes until shattering.','Parmesan in the last 5. Cold sour cream on the side.'],'Thinner smash = more crunch. Commit.',[8,42,16],'warm'),
R('r21','Mushroom risotto','🍄','Mains','Italian',50,'Hard',580,['impress','comfort','vegetarian'],['arborio rice','mushrooms','butter','parmesan','onion','garlic','white wine','vegetable broth','thyme'],['Sear mushrooms hard in butter until golden; set aside.','Toast the rice in the same pan until the edges turn glassy.','Wine in; let it vanish. Then hot broth, one ladle at a time, stirring.','At 18 minutes: mushrooms back, butter, parmesan, beat it glossy. Rest 2 minutes.'],'The final beating (mantecatura) makes it creamy — not cream.',[16,68,24],'earth'),
R('r22','French omelette','🍳','Breakfast','French',10,'Medium',320,['fast','vegetarian','high-protein'],['eggs','butter','green onion','parmesan'],['Beat three eggs until completely uniform — no streaks.','Butter foaming in a nonstick pan; eggs in, stirring fast with a fork.','When softly set, stop. Tilt, fold in thirds, roll onto the plate seam-down.','Gloss with butter. Chives (or green onion) over.'],'It should never take color. Pale gold, custardy middle.',[20,2,26],'warm'),
R('r23','Overnight oats','🌾','Breakfast','American',5,'Easy',350,['healthy','fast','sweet','cheap'],['oats','yogurt','milk','honey','blueberries','almonds','cinnamon'],['Stir oats, yogurt, milk, honey and cinnamon in a jar.','Lid on, fridge, overnight — no shortcuts, the oats need the hours.','Morning: loosen with a splash of milk.','Blueberries and toasted almonds on top.'],'Make three jars on Sunday. Thank yourself Wednesday.',[14,48,10],'fresh'),
R('r24','Teriyaki salmon bowls','🍱','Healthy','Japanese',25,'Easy',540,['healthy','fast','high-protein'],['salmon','rice','soy sauce','honey','ginger','garlic','broccoli','sesame seeds'],['Simmer soy, honey, ginger and garlic until it coats a spoon.','Roast broccoli hot until the edges frazzle.','Sear salmon; brush with glaze in the last 2 minutes, twice.','Rice, broccoli, salmon, more glaze, sesame seeds.'],'Glaze burns fast — brush late, watch close.',[40,56,18],'fresh'),
R('r25','Skillet chocolate chip cookie','🍪','Desserts','American',35,'Easy',720,['comfort','sweet','impress'],['butter','brown sugar','sugar','eggs','flour','chocolate chips','vanilla extract','ice cream'],['Brown the butter until it smells like hazelnuts. Cool slightly.','Whisk in both sugars, then egg and vanilla.','Fold in flour and an irresponsible amount of chocolate.','Press into the skillet; 180°C for 18 minutes — edges set, middle molten. Ice cream on while hot.'],'Underbake it. The skillet keeps cooking after.',[8,84,34],'warm'),
R('r26','Lemon yogurt cake','🍋','Desserts','French',60,'Easy',420,['sweet'],['flour','sugar','eggs','yogurt','lemon','olive oil','baking powder','powdered sugar'],['Whisk yogurt, sugar, eggs and a storm of lemon zest.','Fold in flour and baking powder, then stream in the olive oil.','Loaf tin, 175°C, 45 minutes until a skewer comes out clean.','Lemon juice + powdered sugar glaze over the warm cake.'],'The olive oil keeps it moist for days. If it lasts days.',[7,58,16],'fresh'),
R('r27','Dark chocolate mousse','🍫','Desserts','French',25,'Medium',460,['impress','sweet'],['dark chocolate','heavy cream','eggs','sugar'],['Melt chocolate gently; cool until just warm to the touch.','Whip cream to soft, floppy peaks.','Whisk yolks and sugar until pale; fold into the chocolate.','Fold in cream in three additions — keep the air. Chill 2 hours.'],'Fold like you mean it, gently. The bubbles are the dessert.',[8,32,30],'earth'),
R('r28','Banana bread','🍌','Desserts','American',70,'Easy',380,['cheap','comfort','sweet'],['banana','flour','butter','brown sugar','eggs','baking soda','walnuts','cinnamon'],['Mash three embarrassingly ripe bananas.','Beat in melted butter, brown sugar, then eggs.','Fold in flour, baking soda, cinnamon and walnuts — stop at "just mixed".','Loaf tin, 175°C, 55–60 minutes. Cool before slicing (attempt to, anyway).'],'Black-spotted bananas only. Yellow ones are for eating.',[7,52,18],'warm'),
R('r29','White bean & kale soup','🫘','Healthy','Italian',35,'Easy',360,['soup','healthy','cheap','vegetarian'],['white beans','kale','carrot','celery','onion','garlic','vegetable broth','parmesan','chili flakes','lemon'],['Sweat onion, carrot and celery in olive oil, 8 minutes.','Garlic and chili flakes, then broth and beans; simmer 15.','Mash a cup of beans against the pot to thicken.','Kale in for the last 5. Lemon and parmesan to serve.'],'A parmesan rind in the pot is the free upgrade.',[16,44,10],'fresh'),
R('r30','Roasted cauliflower tacos','🌮','Healthy','Mexican',35,'Easy',430,['vegetarian','healthy'],['cauliflower','tortillas','chili powder','cumin','avocado','lime','cabbage','yogurt','cilantro'],['Toss cauliflower florets in oil, chili powder and cumin.','Roast at 220°C for 25 minutes until charred at the tips.','Stir lime into yogurt; shred the cabbage fine.','Warm tortillas, yogurt swoosh, cauliflower, cabbage, avocado, cilantro.'],'Char equals flavor. Pale cauliflower is a rumor of a taco.',[12,48,18],'fresh'),
R('r31','Mediterranean chickpea bowls','🥗','Healthy','Mediterranean',25,'Easy',470,['healthy','fast','vegetarian','salad'],['chickpeas','quinoa','cucumber','cherry tomatoes','feta','olives','lemon','olive oil','mint'],['Cook quinoa; spread on a plate to cool and fluff.','Crisp the chickpeas in olive oil with a pinch of cumin.','Chop cucumber and tomatoes; tear the mint.','Build bowls, feta and olives over, lemon + oil as the dressing.'],'Warm chickpeas on cold salad — the contrast carries it.',[18,52,22],'fresh'),
R('r32','Gambas al ajillo','🦐','Mains','Spanish',15,'Easy',380,['fast','impress','high-protein'],['shrimp','garlic','olive oil','chili flakes','parsley','lemon','bread'],['Warm a scary amount of sliced garlic in olive oil — gentle, until pale gold.','Chili flakes, then shrimp in a single layer. 90 seconds a side.','Off heat: lemon and parsley.','Bring the pan to the table with bread for the oil. The oil is the dish.'],'Overcooked shrimp is a crime with a 3-minute statute.',[28,12,26],'heat'),
R('r33','Steak with herb butter','🥩','Mains','French',30,'Medium',720,['impress','high-protein'],['steak','butter','garlic','thyme','rosemary','potato'],['Salt the steak an hour ahead if you can. Dry it like it insulted you.','Ripping-hot cast iron: 2 minutes, flip, 2 minutes.','Butter, garlic, herbs in; baste on a tilt for 2 more.','Rest 8 minutes — as long as it cooked. Slice against the grain.'],'The rest is not optional. The rest is the recipe.',[48,2,52],'earth'),
R('r34','Rainbow veggie stir-fry','🥦','Quick & Easy','Chinese',20,'Easy',380,['vegan','healthy','fast','cheap','one-pan'],['broccoli','bell pepper','carrot','mushrooms','garlic','ginger','soy sauce','sesame oil','rice','cornstarch'],['Stir soy, sesame oil, cornstarch and a splash of water into a slurry.','Wok on max: broccoli and carrot first, 3 minutes.','Peppers, mushrooms, garlic, ginger — 2 more.','Sauce in; it thickens in 30 seconds. Over rice.'],'Hot wok, dry vegetables, no crowding. Steam is the enemy.',[10,58,10],'fresh'),
R('r35','Caprese with good tomatoes','🍅','Sides','Italian',10,'Easy',310,['salad','fast','vegetarian','impress'],['tomato','mozzarella','basil','balsamic vinegar','olive oil'],['Slice tomatoes and mozzarella the same thickness.','Shingle on a platter, alternating, basil leaves tucked between.','Best olive oil you own, thread of balsamic, flaky salt.','Serve at room temperature — cold mutes tomatoes.'],'This dish is only as good as the tomato. Shop accordingly.',[14,8,24],'fresh')
];
// ---- Amount table: [regex, qtyPerServing, unit, prep] — first match wins, specific before general
const AMOUNTS=[
['sesame oil',0.5,'tsp','to finish'],['olive oil',0.5,'tbsp',''],['vegetable oil',0.5,'tbsp',''],
['garlic',1,'clove','minced'],['ginger',0.5,'inch','grated'],['green onion',1,'','sliced thin'],['red onion',0.25,'','shaved thin'],['onion|shallot|leek',0.5,'','diced'],
['butter',15,'g','cold, cubed'],['heavy cream',60,'ml',''],['sour cream|greek yogurt|yogurt',60,'g',''],['buttermilk',120,'ml',''],['milk',80,'ml',''],['cream cheese|ricotta',40,'g',''],
['parmesan',15,'g','finely grated'],['feta|goat cheese|blue cheese',25,'g','crumbled'],['cheddar|mozzarella|halloumi',30,'g','grated'],
['eggs',1,'',''],
['arborio rice',75,'g',''],['rice noodles|egg noodles|ramen noodles',85,'g','dry'],['rice vinegar|balsamic vinegar|wine vinegar|cider vinegar',1,'tsp',''],['rice',75,'g','rinsed'],
['spaghetti|penne|pasta|orzo',90,'g','dry'],['quinoa|couscous',60,'g','rinsed'],['oats',50,'g',''],
['flour',60,'g','spooned and levelled'],['powdered sugar',20,'g','sifted'],['brown sugar',25,'g','packed'],['sugar',20,'g',''],['baking powder|baking soda',0.25,'tsp',''],['cornstarch',0.5,'tsp',''],['vanilla extract',0.25,'tsp',''],['chocolate chips|dark chocolate',40,'g','roughly chopped'],['cocoa powder',10,'g',''],
['chicken breast',1,'','about 170 g each'],['chicken thighs',2,'','boneless'],['ground beef|ground turkey',110,'g',''],['steak',1,'','about 220 g, room temp'],['salmon|white fish',1,'fillet','about 150 g'],['shrimp',110,'g','peeled and deveined'],['bacon',2,'slices',''],['tofu',100,'g','pressed, cubed'],
['chicken broth|vegetable broth|beef broth',250,'ml','hot'],['coconut milk',0.5,'can','full-fat'],['canned tomatoes',0.5,'can','400 g'],['tomato paste',0.5,'tbsp',''],
['chickpeas|black beans|white beans|kidney beans|lentils',0.5,'can','drained and rinsed'],
['soy sauce|fish sauce|oyster sauce|hoisin sauce|worcestershire',0.5,'tbsp',''],['miso paste|gochujang|harissa|curry paste',0.75,'tbsp',''],['sriracha|hot sauce',0.5,'tsp','or to taste'],['honey|maple syrup',0.5,'tbsp',''],['mustard|mayonnaise|ketchup|pesto|salsa|bbq sauce|tahini',0.5,'tbsp',''],
['chili flakes|cayenne',0.125,'tsp',''],['cumin|paprika|chili powder|garam masala|turmeric|curry powder|oregano|cinnamon|five spice|za\'atar',0.5,'tsp',''],['nutmeg|saffron',1,'pinch',''],['bay leaves',0.5,'leaf',''],
['cilantro|parsley|basil|mint|dill',1,'tbsp','leaves, torn'],['thyme|rosemary',0.5,'sprig',''],
['lemon|lime',0.5,'','half zested, half juiced'],['avocado',0.5,'','sliced'],['banana',0.75,'','very ripe'],['blueberries|strawberries|frozen berries',50,'g',''],
['spinach|kale|arugula',60,'g','washed'],['cabbage|lettuce',50,'g','shredded'],['cherry tomatoes',80,'g','halved'],['tomato',1,'','cut in wedges'],['bell pepper',0.5,'','sliced'],['jalapeño',0.25,'','sliced thin'],['mushrooms',60,'g','torn'],['broccoli|cauliflower',100,'g','in florets'],['carrot',0.5,'','ribboned'],['celery',0.5,'stalk','diced'],['potato|sweet potato',150,'g','scrubbed'],['zucchini|eggplant|cucumber',0.5,'','chopped'],['green beans|asparagus|frozen peas|frozen corn|corn|edamame',60,'g',''],['kimchi',60,'g','chopped, with juice'],
['peanuts|almonds|walnuts|cashews|pecans|pistachios|pine nuts',15,'g','toasted'],['peanut butter|almond butter',1,'tbsp',''],['sesame seeds',0.5,'tsp','toasted'],['breadcrumbs|panko',20,'g',''],
['tortillas|pita',1.5,'',''],['sourdough bread|bread',1.5,'slices',''],['nori',0.5,'sheet',''],['olives',20,'g',''],['capers',0.5,'tbsp','rinsed'],['white wine|red wine',40,'ml','dry'],['ice cream',1,'scoop','vanilla, obviously'],['puff pastry',0.25,'sheet','thawed']
];
// ---- Hard-filter word lists
const BLOCKED={
 'Peanuts':['peanut','peanut butter'],
 'Tree nuts':['almond','walnut','cashew','pecan','pistachio','pine nut','hazelnut'],
 'Shellfish':['shrimp','prawn','crab','lobster','mussel','oyster sauce','oyster','scallop','clam'],
 'Eggs':['egg','mayonnaise'],
 'Soy':['soy','tofu','edamame','miso','hoisin'],
 'Gluten':['flour','pasta','spaghetti','penne','orzo','bread','noodle','tortilla','pita','couscous','panko','breadcrumb','pastry','ramen','soy sauce','hoisin','beer'],
 'Dairy':['milk','butter','cheese','cream','yogurt','parmesan','mozzarella','cheddar','feta','ricotta','halloumi','buttermilk','ice cream','ghee'],
 'Pork':['pork','bacon','ham','chorizo','prosciutto','sausage'],
 'Sesame':['sesame','tahini'],
 'Fish':['salmon','tuna','anchov','fish sauce','white fish','cod','worcestershire'],
 'Vegetarian':['chicken','beef','steak','pork','bacon','ham','turkey','lamb','sausage','chorizo','salmon','tuna','fish','shrimp','mussel','scallop','anchov','prosciutto'],
 'Vegan':['chicken','beef','steak','pork','bacon','ham','turkey','lamb','sausage','chorizo','salmon','tuna','fish','shrimp','mussel','scallop','anchov','egg','milk','butter','cheese','cream','yogurt','parmesan','mozzarella','cheddar','feta','ricotta','halloumi','honey','ice cream','mayonnaise'],
 'Pescatarian':['chicken','beef','steak','pork','bacon','ham','turkey','lamb','sausage','chorizo'],
 'Halal':['pork','bacon','ham','chorizo','prosciutto','wine','beer','worcestershire'],
 'Kosher':['pork','bacon','ham','chorizo','prosciutto','shrimp','mussel','scallop','oyster','crab','lobster'],
 'Gluten-free':['flour','pasta','spaghetti','penne','orzo','bread','noodle','tortilla','pita','couscous','panko','breadcrumb','pastry','ramen','soy sauce','hoisin','beer'],
 'Dairy-free':['milk','butter','cheese','cream','yogurt','parmesan','mozzarella','cheddar','feta','ricotta','halloumi','buttermilk','ice cream'],
 'Nut-free kitchen':['almond','walnut','cashew','pecan','pistachio','pine nut','peanut'],
 'No alcohol':['wine','beer','kombucha'],
 'Low sodium':['soy sauce','fish sauce','oyster sauce','miso','anchov','bacon','ham','olives','capers','kimchi'],
 'Low FODMAP':['onion','garlic','shallot','leek','cauliflower','mushroom','apple','mango','honey','beans','chickpea','lentil'],
 'Low carb/keto':['rice','pasta','spaghetti','penne','orzo','bread','noodle','tortilla','pita','couscous','quinoa','oats','potato','flour','sugar','maple syrup','banana','polenta'],
 'Paleo':['rice','pasta','bread','noodle','tortilla','flour','sugar','cheese','milk','yogurt','cream','beans','chickpea','lentil','peanut','tofu','soy','oats','corn']
};
// ---- Quiz
const LV=['Skip it','Rarely','Standard','Often','Chase it'];
const QUIZ=[
{id:'allergies',n:1,type:'chips',headline:'Anything that\'s a hard no?',hint:'Allergies first — recipes with these never show up, ever.',options:['Peanuts','Tree nuts','Shellfish','Eggs','Soy','Gluten','Dairy','Pork','Sesame','Fish','Nothing at all'],none:'Nothing at all',custom:true},
{id:'diet',n:2,type:'grid',headline:'How do you eat, most of the time?',hint:'Pick everything that\'s roughly true. We\'ll cook inside the lines.',options:[['Vegetarian','🥦'],['Vegan','🌱'],['Pescatarian','🐟'],['Flexitarian','🥗'],['Low carb/keto','🥑'],['Paleo','🍖'],['Mediterranean','🫒'],['High protein','🥩'],['No restrictions','🍽️']],none:'No restrictions',custom:true},
{id:'rules',n:3,type:'grid',headline:'Any rules we should never break?',hint:'Religious or medical — these are hard filters, not suggestions.',options:[['Halal',''],['Kosher',''],['Gluten-free',''],['Dairy-free',''],['Nut-free kitchen',''],['Low sodium',''],['Low FODMAP',''],['No alcohol',''],['None of these','']],none:'None of these',custom:true},
{id:'flavors',n:4,type:'bars',headline:'Turn the flavor dials.',hint:'Everything starts at standard. Nudge what you love up and what you don\'t, down.',items:['Savory','Sweet','Umami','Garlicky','Tangy / sour','Smoky','Buttery','Herby','Cheesy','Spicy heat','Salty','Bitter / roasty','Nutty','Citrusy'],levels:LV},
{id:'textures',n:5,type:'bars',headline:'Now the textures.',hint:'Same idea — what should dinner feel like?',items:['Crunchy','Crispy edges','Creamy','Chewy','Silky','Juicy','Crusty','Melty','Fluffy','Charred'],levels:LV},
{id:'heat',n:6,type:'tiers',headline:'How much heat can you actually take?',hint:'Be honest. This calibrates every chili in every recipe.',options:[['No heat at all','black pepper is plenty'],['Barely warm','a whisper of paprika'],['Gentle kick','sriracha on the side'],['Properly spicy','bird\'s eye chilies welcome'],['Bring the fire','habanero, hold my drink'],['Reaper tier','we\'re past flavor now']]},
{id:'garlic',n:7,type:'tiers',headline:'And the garlic question.',hint:'There is a correct answer, but we won\'t say which.',options:[['Barely any','a polite suggestion of garlic'],['Normal amount','what the recipe says'],['Extra garlic','double it, always'],['Absurd amount','the recipe is a starting point']]},
{id:'appliances',n:8,type:'grid',headline:'What\'s on your counter?',hint:'We\'ll only ever hand you recipes your kitchen can actually make.',options:[['Stovetop',''],['Oven',''],['Microwave',''],['Air fryer',''],['Instant Pot',''],['Slow cooker',''],['Rice cooker',''],['Blender',''],['Food processor',''],['Stand mixer',''],['Hand mixer',''],['Outdoor grill',''],['Toaster oven',''],['Waffle iron',''],['Sous vide',''],['Espresso machine',''],['Toaster',''],['Kettle','']]},
{id:'cookware',n:9,type:'grid',headline:'And in the cupboard?',hint:'Pots and pans we can count on.',options:[['Nonstick skillet',''],['Cast iron',''],['Wok',''],['Sheet pan',''],['Dutch oven',''],['Saucepan',''],['Stockpot',''],['Baking dish',''],['Mixing bowls',''],['Sharp knife','']]},
{id:'cuisines',n:10,type:'grid',headline:'Which cuisines make you happiest?',hint:'Pick as many as you like — this shapes what leads your feed.',options:[['Italian','🍝'],['Mexican','🌮'],['Japanese','🍣'],['Chinese','🥡'],['Thai','🍛'],['Indian','🫓'],['Korean','🍲'],['Vietnamese','🍜'],['Mediterranean','🫒'],['Middle Eastern','🧆'],['Greek','🥗'],['French','🥐'],['Spanish','🥘'],['American','🍔'],['Moroccan','🍋'],['Caribbean','🍍'],['Ethiopian','🌶️'],['German','🥨']]},
{id:'meals',n:11,type:'grid',headline:'What do you cook most?',hint:'So we lead with the meals you actually make.',options:[['Breakfast','🍳'],['Lunch','🥪'],['Dinner','🍽️'],['Snacks','🥨'],['Desserts','🍰'],['Meal prep','🍱'],['Late night','🌙']]},
{id:'dislikes',n:12,type:'chips',headline:'Ingredients you just don\'t like?',hint:'Not allergies — just the ones that ruin a dish for you.',options:['Cilantro','Olives','Mushrooms','Blue cheese','Anchovies','Beets','Liver','Raisins','Coconut','Tofu','Eggplant','Pickles','Fennel'],custom:true},
{id:'constants',n:13,type:'chips',headline:'What\'s always in your kitchen?',hint:'Pick your constants — we\'ll stock your pantry with them right now.',options:['garlic','onion','eggs','butter','chicken breast','rice','pasta','potato','canned tomatoes','spinach','cheddar','parmesan','yogurt','lemon','black beans','chickpeas','ground beef','tofu','bell pepper','mushrooms','ginger','soy sauce','tortillas','oats'],custom:true},
{id:'skill',n:14,type:'tiers',headline:'How comfortable are you in a kitchen?',hint:'No judgment either way — this sets how much hand-holding recipes give.',options:[['Beginner','tell me everything, twice'],['Comfortable','I can follow a recipe fine'],['Confident','I improvise on weeknights'],['Chef-level','I own a fish spatula and use it']]},
{id:'time',n:15,type:'tiers',headline:'A normal weeknight — how long do you give dinner?',hint:'This becomes your default time filter in Discover.',options:[['15 minutes','in and out'],['30 minutes','the sweet spot'],['45 minutes','happy to potter'],['An hour or more','cooking is the evening']]},
{id:'household',n:16,type:'tiers',headline:'Who are you cooking for?',hint:'We\'ll scale every recipe to the right number of plates.',options:[['Just me','portions for one'],['Two of us','dinner for two'],['Three or four','family table'],['Five or more','feeding a crowd']]},
{id:'budget',n:17,type:'tiers',headline:'Grocery budget?',hint:'We\'ll respect it when suggesting what to cook.',options:[['As cheap as it gets','beans are beautiful'],['Reasonable','normal shop, no caviar'],['Whatever it takes','the good parmesan']]},
{id:'goals',n:18,type:'chips',headline:'What are you cooking towards?',hint:'Pick a few — recipes that serve them get a quiet boost.',options:['More protein','Waste less','Eat more veg','Spend less','Meal prep','Learn technique','Eat less sugar','Cook faster'],custom:true},
{id:'macros',n:19,type:'sliders',headline:'Shape your plate.',hint:'Everything starts at standard. The plate redraws as you pull the sliders.',plate:['Vegetables','Fruit','Grains','Protein','Dairy'],dials:['Calories','Sugar','Protein','Carbs'],labels:['way less','less','a little less','standard','a little more','more','way more']},
{id:'ab',n:20,type:'ab',headline:'Last one — which plate wins?',hint:'Gut answer. No overthinking.',options:[['Crispy & charred','🔥','edges, crust, smoke, drama'],['Silky & slow','🥄','braises, cream, spoon-tender']]}
];
const PRIORITIES=['Fast','Healthy','Cheap','Comfort','High Protein','Impress Someone','Low Effort Cleanup'];
const COURSES=['Soup','Sides','Salad'];
const TABS=[
{key:'all',label:'All saved',theme:'Everything, in one warm place',art:'assets/tab-all-saved.jpg',accent:'var(--honey-butter)'},
{key:'favorites',label:'Favorites',theme:'Proven winners — cooked and loved',art:'assets/tab-favorites.jpg',accent:'var(--paprika)'},
{key:'Breakfast',label:'Breakfast',theme:'Golden mornings',art:'assets/tab-breakfast.jpg',accent:'var(--honey-butter)'},
{key:'Mains',label:'Mains',theme:'The main event',art:'assets/tab-mains.jpg',accent:'var(--terracotta)'},
{key:'Sides',label:'Sides',theme:'Small plates, big opinions',art:'assets/tab-sides.jpg',accent:'var(--sage-leaf)'},
{key:'Desserts',label:'Desserts',theme:'The sweet ending',art:'assets/tab-desserts.jpg',accent:'var(--paprika)'},
{key:'Quick & Easy',label:'Quick & easy',theme:'Twenty minutes, tops',art:'assets/tab-quick-easy.jpg',accent:'var(--honey-butter)'},
{key:'Comfort Food',label:'Comfort food',theme:'A hug on a plate',art:'assets/tab-comfort-food.jpg',accent:'var(--terracotta)'},
{key:'Healthy',label:'Healthy',theme:'Fresh and unfussy',art:'assets/tab-healthy.jpg',accent:'var(--sage-leaf)'}
];
window.TB_DATA={CATS,CATALOG,STAPLES_PRESET,ASSUMED,RECIPES,AMOUNTS,BLOCKED,QUIZ,PRIORITIES,COURSES,TABS};
})();
